### ISSUE TITLE
urequest.py missing and alternate solution proposal

### ISSUE THREAD

**Issue by rafaelaroca** [Wiznet/RP2040-HAT-MicroPython#2]
Hello, 

The file urequest.py mentioned in the instructions is missing.

By the way, the instructions at the README and the HTTP example proposed the use of urequest.py instead of the official urequests.py. Maybe because urequests.py fails with WIZnet W5100S-EVB-Pico.

I made a fix that allows W5100S-EVB-Pico to use the official urequests.py. The fix is here:

https://github.com/micropython/micropython/issues/8298

By the way, I have prepared BIPES to allow block-based programming with Ethernet. Works nicely and is quite straightforward for most users. Take a look:

[BIPES and Raspberry Pi Pico Ethernet](https://rafaelaroca.wordpress.com/2022/02/13/bipes-and-raspberry-pi-pico-ethernet/)

and

[Building MicroPython for the Raspberry Pi PICO with Ethernet and WebREPL support](https://rafaelaroca.wordpress.com/2022/02/13/building-micropython-for-the-raspberry-pi-pico-with-ethernet-and-webrepl-support/)

thanks!

**Comment by irinakim12** [comment]
thanks~! We will review the part you pointed out and correct it.
