### ISSUE TITLE
Firmware with WebREPL

### ISSUE THREAD

**Issue by rafaelaroca** [Wiznet/RP2040-HAT-MicroPython#5]
Hello, is it possible to generate a firmware version for the RP2040-HAT to get WebREPL over Ethernet? This would be amazing to program the board over the network!

Thanks!
Rafael

**Comment by irinakim12** [comment]
From what I've checked, WebREPL is available in the wifi module. 
I also think that it would be good if support is possible. 
It will take a long time to apply it.

**Comment by rafaelaroca** [comment]
Did you add WebREPL? Or just closed? Just curios :-)
